export const weights = {
  Name: 1,
  Address: 1,
  Location: 1,
  Gender: 1,
  Employer: 2,
  DoB: 2,
  Education: 1,
  "Birth Place": 2,
  "Personal Cell": 0.5,
  Email: 0.1,
  "Business Phone": 0.1,
  "Facebook Account": 1,
  "Twitter Account": 0.1,
  "Instagram Account": 0.1,
  DDL: 2,
  "Passport #": 2,
  "Credit Card": 2,
  SSN: 10,
};

export const willingness_measures = {
  Name: 1.0,
  Address: 0.1,
  Location: 0.1,
  "Birth Place": 0.2,
  DoB: 0.83,
  "Personal Cell": 0.16,
  Gender: 0.98,
  Employer: 0.5,
  Education: 0.8,
  Email: 0.7,
  "Business Phone": 0.4,
  "Facebook Account": 0.9,
  "Twitter Account": 0.9,
  "Instagram Account": 0.9,
  DDL: 0.2,
  "Passport #": 0.05,
  "Credit Card": 0.02,
  SSN: 0.01,
};

export const resolution_powers = {
  Name: 0.1,
  Address: 0.3,
  Location: 0.1,
  DoB: 0.7,
  "Personal Cell": 0.9,
  Email: 0.95,
  "Business Phone": 0.4,
  "Facebook Account": 0.8,
  "Twitter Account": 0.8,
  "Instagram Account": 0.8,
  DDL: 1.0,
  "Passport #": 1.0,
  "Credit Card": 1.0,
  SSN: 1.0,
  Gender: 0.1,
  Employer: 0.2,
  Education: 0.3,
  "Birth Place": 0.5,
};

export const beta_coefficients = {
  Name: 1,
  Address: 1,
  Location: 1,
  DoB: 1,
  "Personal Cell": 1,
  Email: 1,
  "Business Phone": 1,
  "Facebook Account": 1,
  "Twitter Account": 1,
  "Instagram Account": 1,
  DDL: 1,
  "Passport #": 1,
  "Credit Card": 1,
  SSN: 1,
  Gender: 1,
  Employer: 1,
  Education: 1,
  "Birth Place": 1,
};
